name: Build Android app

on: workflow_dispatch

jobs:
  ci:
    runs-on: macos-latest
    timeout-minutes: 600
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up disaster recovery network
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: 

    - name: Well, that's not good. Go fix it yourself
      if: ${{ failure() }}
      # PS: The command below is stolen from https://github.com/dikeckaan/MacOS-Workflow-VNC but using tailscale instead of crappy ngrok haha
      run: |
        sudo mdutil -i off -a
        sudo dscl . -create /Users/scello
        sudo dscl . -create /Users/scello UserShell /bin/bash
        sudo dscl . -create /Users/scello RealName "SpruceCello125"
        sudo dscl . -create /Users/scello UniqueID 1001
        sudo dscl . -create /Users/scello PrimaryGroupID 80
        sudo dscl . -create /Users/scello NFSHomeDirectory /Users/scello
        sudo dscl . -passwd /Users/scello $1
        sudo dscl . -passwd /Users/scello $1
        sudo createhomedir -c -u scello > /dev/null
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 
        echo $2 | perl -we 'BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA"}; $_ = <>; chomp; s/^(.{8}).*/$1/; @p = unpack "C*", $_; foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) }; print "\n"' | sudo tee /Library/Preferences/com.apple.VNCSettings.txt
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
        echo Now go fix it asap (and push compiled .apk yourself)
        sleep infinity